% generated by ChatGPT 5
% prompt: in matlab, I have two 3d vectors u and v.
%         Is there a way of finding a quaternion
%         representing the rotation from u to v?

function q = quat_from_u_to_v(u, v)
    % u, v: 3x1 or 1x3 real vectors (need not be unit)
    u = u(:); v = v(:);
    nu = norm(u); nv = norm(v);
    assert(nu>0 && nv>0, 'u and v must be nonzero');

    u = u/nu; v = v/nv;
    c = cross(u, v);
    d = dot(u, v);

    % Tolerances
    tol = 1e-12;

    if d > 1 - tol
        % Vectors almost identical: zero rotation
        q = [1 0 0 0];
        return
    elseif d < -1 + tol
        % Vectors nearly opposite: pick any axis ⟂ u
        % Find a vector orthogonal to u in a stable way
        [~, idx] = min(abs(u));          % smallest component
        tmp = zeros(3,1); tmp(idx) = 1;  % unit basis with least overlap
        axis = cross(u, tmp);
        axis = axis / norm(axis);
        angle = pi;
        q = [cos(angle/2), axis.'*sin(angle/2)];
        return
    else
        % General case
        s = sqrt((1+d)*2);   % = 2*cos(theta/2)
        axis = c / s;        % normalized rotation axis
        q = [s/2, axis.'];   % [w x y z]
        % (Equivalent to w = sqrt((1+d)/2), vec = c/(2*w))
    end

    % Normalize to protect against roundoff
    q = q / norm(q);
end